description: "A new Flutter application."
name: "Nimedix"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^1.0.5"
  path_drawing: "^1.0.0"
  flutter:
    sdk: "flutter"
  fluttertoast: ^8.0.9
dev_dependencies:
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Poppins"
      fonts: 
        - 
          asset: "fonts/Poppins-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Poppins-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Poppins-600.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "fonts/Poppins-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Montserrat"
      fonts: 
        - 
          asset: "fonts/Montserrat-700.ttf"
          style: "normal"
          weight: 700
  uses-material-design: true
